### ISSUE TITLE
On edit, some projects say view error that there is not string resource

### ISSUE THREAD

**Issue by indication** [indication/android-form-edittext#1]
The following classes could not be instantiated:
- com.andreabaccega.widget.FormEditText (Open Class, Show Error Log)
  See the Error Log (Window > Show View) for more details.
  Tip: Use View.isInEditMode() in your custom views to skip code when shown in Eclipse

android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7F050004.
    at com.android.layoutlib.bridge.android.BridgeResources.throwException(BridgeResources.java:648)
    at com.android.layoutlib.bridge.android.BridgeResources.getString(BridgeResources.java:461)
    at android.content.Context.getString(Context.java:183)
    at com.andreabaccega.widget.FormEditText.<init>(FormEditText.java:143)
    at com.andreabaccega.widget.FormEditText.<init>(FormEditText.java:72)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.instantiateClass(ProjectCallback.java:422)
    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.loadView(ProjectCallback.java:179)
    at com.android.layoutlib.bridge.android.BridgeInflater.loadCustomView(BridgeInflater.java:205)
    at com.android.layoutlib.bridge.android.BridgeInflater.createViewFromTag(BridgeInflater.java:133)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:296)

**Comment by indication** [comment]
make patch and send pull request near the week

**Comment by indication** [comment]
It occurred on eclipse not in android studio.
